name: Cypress Tests
on: [push]
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 17.x

    - name: Install cypress dependency
      run: npm install --prefix ./cypress_automation cypress

    - name: Install client dependency
      run: npm install --prefix ./client

    - name: Install api dependency
      run: npm install --prefix ./api

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
      
    - name: Cypress test
      run: npm --prefix ./cypress_automation run test

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
