name: Cypress Tests
on: [push]
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 17.x

    - name: Install dependencies
      run: npm install --prefix ./cypress_automation cypress

    - name: Cypress.io
      uses: cypress-io/github-action@v2.9.7
      with:
        command: npm run test

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
